wallpaper {
    monitor = DP-1
    path = /home/eva/Nextcloud/Wallpapers/anders/minceraft/2026-05-11_22.54.13.png
    fit_mode = cover
}
wallpaper {
    monitor = DP-3
    path = /home/eva/Nextcloud/Wallpapers/anders/minceraft/2026-05-11_22.54.13.png
    fit_mode = cover
}
wallpaper {
    monitor = HDMI-A-1
    path = /home/eva/Nextcloud/Wallpapers/anders/minceraft/2026-05-11_22.54.13.png
    fit_mode = cover
}
